export const chars = [
    {
        "allies":["Kya"],
        "enemies":["Zuko"],
        "_id":"5cf5679a915ecad153ab68cb",
        "photoUrl":"https://vignette.wikia.nocookie.net/avatar/images/7/79/Pilot_-_Aang.png/revision/latest?cb=20120311133235",
        "name":"Aang (pilot)",
        "gender":"Male",
        "hair":"Black (typically shaven)",
        "weapon":"Air, ",
        "profession":" Avatar Monk",
        "position":"Avatar-in-training",
        "affiliation":" Air Nomads Team Avatar",
        "first":"Unaired pilot"
    },
    {
        "allies":["Appa"],
        "enemies":["Azula"],
        "_id":"5cf5679a915ecad153ab68c9",
        "photoUrl":"https://vignette.wikia.nocookie.net/avatar/images/a/ae/Aang_at_Jasmine_Dragon.png/revision/latest?cb=20130612174003",
        "name":"Aang",
        "gender":"Male",
        "eye":"Gray",
        "hair":"Dark brown ",
        "skin":"Light",
        "love":"Katara ",
        "weapon":"The elements",
        "profession":" Air Nomad culture teacher Airbending instructor Avatar Monk",
        "position":" Co-founder of the United Republic of Nations Fully Realized Avatar",
        "predecessor":"Roku",
        "affiliation":" Air Acolytes Air Nomads Air Scouts (formerly) Team Avatar","first":"\""
    },
    {
        "allies":["Gyatso"],
        "enemies":["Ozai"],
        "_id":"5cf5679a915ecad153ab68ca",
        "photoUrl":"https://vignette.wikia.nocookie.net/avatar/images/2/21/Into_The_Inferno_Aang.png/revision/latest?cb=20131009060746",
        "name":"Aang (games)",
        "gender":"Male",
        "hair":"Black ",
        "weapon":"The elements, ",
        "profession":"Avatar",
        "position":"Fully Realized Avatar",
        "affiliation":" Air Nomads Team Avatar",
        "first":"Avatar: The Last Airbender video game"
    },
    {
        "allies":["Southern Water Tribe",""],
        "enemies":["Amon"],
        "_id":"5cf5679a915ecad153ab69a1",
        "photoUrl":"https://vignette.wikia.nocookie.net/avatar/images/c/ca/Korra.png/revision/latest?cb=20150406235047",
        "name":"Korra",
        "gender":"Female",
        "eye":"Cyan",
        "hair":"Dark brown",
        "skin":"Brown",
        "love":" Asami Sato (girlfriend)[6] Mako (boyfriend; formerly)",
        "weapon":"The elements",
        "profession":" Avatar Pro-bender (formerly)",
        "position":" Daughter of the Southern Water Tribe chief Fire Ferrets' waterbender (formerly) Fully Realized Avatar[7] Member of Tarrlok's task force (formerly)",
        "predecessor":" Aang (as the Avatar) Hasook (as the waterbending member of the Fire Ferrets) ",
        "affiliation":" Fire Ferrets (formerly) Southern Water Tribe Tarrlok's task force (formerly) Team Avatar",
        "first":"\""
    },
    {
        "allies":["Koko","Yun",""],
        "enemies":["Tagaka"],
        "_id":"5cf5679a915ecad153ab69ac",
        "photoUrl":"https://vignette.wikia.nocookie.net/avatar/images/0/07/Avatar_Kyoshi.png/revision/latest?cb=20140215111846",
        "name":"Kyoshi",
        "gender":"Female",
        "hair":"Brown",
        "love":"Koko's father ",
        "weapon":"The elements",
        "profession":" Avatar Earthbending instructor",
        "position":" Founder of the Kyoshi Warriors and Dai Li Fully Realized Avatar Governor of Kyoshi Island (formerly)[3]",
        "predecessor":"Kuruk",
        "affiliation":"Kyoshi Island inhabitants",
        "first":" \"The Southern Air Temple\"(statue and painting) \"The Avatar State\"(vision)"
    }
]